version: '3.1'

services:
  mysql:
    image: mysql:8.0.18
    container_name: nestjs_mysql
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nestjs
      MYSQL_USER: nestjs
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
